### PR TITLE
"Memories, Reappear" init (my last level)

### PR DESCRIPTION
**Pull request by C-Viridian-19053**
-- add my last level.

### CODE REVIEW

**Comment by vindowvipre** [comment]
Your level has a repeated error `'for' step must be a number` occasionally in onStep. I'd recommend fixing that first.

**Comment by C-Viridian-19053** [comment]
at line where?

**Comment by C-Viridian-19053** [comment]
oh ye! it's a `cAltBarrage` thingy! will be fix soon.

**Comment by Syyrion** [comment]
If you are using any functions that could come from a library, then replace them with the library version. Trim out any unused functions if needed.

**Pull request merged**
